// File was generated by 'scripts/generate_filter.py'
// DO NOT MODIFY!
// Fast And Furious column database
// Author: Jacek Migdal <jacek@migdal.pl>

#ifndef FILTER_H
#define FILTER_H
template<class T>
int filterPrimitive(T* target, T* source, unsigned char current, int rest) {
  switch (current) {
    case 0x0:
      return 0;
    case 0x1:
      target[rest + 0] = source[0];
      return 1;
    case 0x2:
      target[rest + 0] = source[1];
      return 1;
    case 0x3:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      return 2;
    case 0x4:
      target[rest + 0] = source[2];
      return 1;
    case 0x5:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      return 2;
    case 0x6:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      return 2;
    case 0x7:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      return 3;
    case 0x8:
      target[rest + 0] = source[3];
      return 1;
    case 0x9:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      return 2;
    case 0xa:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      return 2;
    case 0xb:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      return 3;
    case 0xc:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      return 2;
    case 0xd:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      return 3;
    case 0xe:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      return 3;
    case 0xf:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      return 4;
    case 0x10:
      target[rest + 0] = source[4];
      return 1;
    case 0x11:
      target[rest + 0] = source[0];
      target[rest + 1] = source[4];
      return 2;
    case 0x12:
      target[rest + 0] = source[1];
      target[rest + 1] = source[4];
      return 2;
    case 0x13:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[4];
      return 3;
    case 0x14:
      target[rest + 0] = source[2];
      target[rest + 1] = source[4];
      return 2;
    case 0x15:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      return 3;
    case 0x16:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      return 3;
    case 0x17:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[4];
      return 4;
    case 0x18:
      target[rest + 0] = source[3];
      target[rest + 1] = source[4];
      return 2;
    case 0x19:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      return 3;
    case 0x1a:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      return 3;
    case 0x1b:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      return 4;
    case 0x1c:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      return 3;
    case 0x1d:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      return 4;
    case 0x1e:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      return 4;
    case 0x1f:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[4];
      return 5;
    case 0x20:
      target[rest + 0] = source[5];
      return 1;
    case 0x21:
      target[rest + 0] = source[0];
      target[rest + 1] = source[5];
      return 2;
    case 0x22:
      target[rest + 0] = source[1];
      target[rest + 1] = source[5];
      return 2;
    case 0x23:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[5];
      return 3;
    case 0x24:
      target[rest + 0] = source[2];
      target[rest + 1] = source[5];
      return 2;
    case 0x25:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[5];
      return 3;
    case 0x26:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[5];
      return 3;
    case 0x27:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[5];
      return 4;
    case 0x28:
      target[rest + 0] = source[3];
      target[rest + 1] = source[5];
      return 2;
    case 0x29:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      return 3;
    case 0x2a:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      return 3;
    case 0x2b:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      return 4;
    case 0x2c:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      return 3;
    case 0x2d:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      return 4;
    case 0x2e:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      return 4;
    case 0x2f:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[5];
      return 5;
    case 0x30:
      target[rest + 0] = source[4];
      target[rest + 1] = source[5];
      return 2;
    case 0x31:
      target[rest + 0] = source[0];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      return 3;
    case 0x32:
      target[rest + 0] = source[1];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      return 3;
    case 0x33:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      return 4;
    case 0x34:
      target[rest + 0] = source[2];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      return 3;
    case 0x35:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      return 4;
    case 0x36:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      return 4;
    case 0x37:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      return 5;
    case 0x38:
      target[rest + 0] = source[3];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      return 3;
    case 0x39:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      return 4;
    case 0x3a:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      return 4;
    case 0x3b:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      return 5;
    case 0x3c:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      return 4;
    case 0x3d:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      return 5;
    case 0x3e:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      return 5;
    case 0x3f:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[4];
      target[rest + 5] = source[5];
      return 6;
    case 0x40:
      target[rest + 0] = source[6];
      return 1;
    case 0x41:
      target[rest + 0] = source[0];
      target[rest + 1] = source[6];
      return 2;
    case 0x42:
      target[rest + 0] = source[1];
      target[rest + 1] = source[6];
      return 2;
    case 0x43:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[6];
      return 3;
    case 0x44:
      target[rest + 0] = source[2];
      target[rest + 1] = source[6];
      return 2;
    case 0x45:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[6];
      return 3;
    case 0x46:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[6];
      return 3;
    case 0x47:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[6];
      return 4;
    case 0x48:
      target[rest + 0] = source[3];
      target[rest + 1] = source[6];
      return 2;
    case 0x49:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[6];
      return 3;
    case 0x4a:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[6];
      return 3;
    case 0x4b:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[6];
      return 4;
    case 0x4c:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[6];
      return 3;
    case 0x4d:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[6];
      return 4;
    case 0x4e:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[6];
      return 4;
    case 0x4f:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[6];
      return 5;
    case 0x50:
      target[rest + 0] = source[4];
      target[rest + 1] = source[6];
      return 2;
    case 0x51:
      target[rest + 0] = source[0];
      target[rest + 1] = source[4];
      target[rest + 2] = source[6];
      return 3;
    case 0x52:
      target[rest + 0] = source[1];
      target[rest + 1] = source[4];
      target[rest + 2] = source[6];
      return 3;
    case 0x53:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      return 4;
    case 0x54:
      target[rest + 0] = source[2];
      target[rest + 1] = source[4];
      target[rest + 2] = source[6];
      return 3;
    case 0x55:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      return 4;
    case 0x56:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      return 4;
    case 0x57:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[4];
      target[rest + 4] = source[6];
      return 5;
    case 0x58:
      target[rest + 0] = source[3];
      target[rest + 1] = source[4];
      target[rest + 2] = source[6];
      return 3;
    case 0x59:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      return 4;
    case 0x5a:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      return 4;
    case 0x5b:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[6];
      return 5;
    case 0x5c:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      return 4;
    case 0x5d:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[6];
      return 5;
    case 0x5e:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[6];
      return 5;
    case 0x5f:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[4];
      target[rest + 5] = source[6];
      return 6;
    case 0x60:
      target[rest + 0] = source[5];
      target[rest + 1] = source[6];
      return 2;
    case 0x61:
      target[rest + 0] = source[0];
      target[rest + 1] = source[5];
      target[rest + 2] = source[6];
      return 3;
    case 0x62:
      target[rest + 0] = source[1];
      target[rest + 1] = source[5];
      target[rest + 2] = source[6];
      return 3;
    case 0x63:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      return 4;
    case 0x64:
      target[rest + 0] = source[2];
      target[rest + 1] = source[5];
      target[rest + 2] = source[6];
      return 3;
    case 0x65:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      return 4;
    case 0x66:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      return 4;
    case 0x67:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      return 5;
    case 0x68:
      target[rest + 0] = source[3];
      target[rest + 1] = source[5];
      target[rest + 2] = source[6];
      return 3;
    case 0x69:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      return 4;
    case 0x6a:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      return 4;
    case 0x6b:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      return 5;
    case 0x6c:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      return 4;
    case 0x6d:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      return 5;
    case 0x6e:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      return 5;
    case 0x6f:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[5];
      target[rest + 5] = source[6];
      return 6;
    case 0x70:
      target[rest + 0] = source[4];
      target[rest + 1] = source[5];
      target[rest + 2] = source[6];
      return 3;
    case 0x71:
      target[rest + 0] = source[0];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      return 4;
    case 0x72:
      target[rest + 0] = source[1];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      return 4;
    case 0x73:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      return 5;
    case 0x74:
      target[rest + 0] = source[2];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      return 4;
    case 0x75:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      return 5;
    case 0x76:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      return 5;
    case 0x77:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[6];
      return 6;
    case 0x78:
      target[rest + 0] = source[3];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      return 4;
    case 0x79:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      return 5;
    case 0x7a:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      return 5;
    case 0x7b:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[6];
      return 6;
    case 0x7c:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      return 5;
    case 0x7d:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[6];
      return 6;
    case 0x7e:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[6];
      return 6;
    case 0x7f:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[4];
      target[rest + 5] = source[5];
      target[rest + 6] = source[6];
      return 7;
    case 0x80:
      target[rest + 0] = source[7];
      return 1;
    case 0x81:
      target[rest + 0] = source[0];
      target[rest + 1] = source[7];
      return 2;
    case 0x82:
      target[rest + 0] = source[1];
      target[rest + 1] = source[7];
      return 2;
    case 0x83:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[7];
      return 3;
    case 0x84:
      target[rest + 0] = source[2];
      target[rest + 1] = source[7];
      return 2;
    case 0x85:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[7];
      return 3;
    case 0x86:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[7];
      return 3;
    case 0x87:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[7];
      return 4;
    case 0x88:
      target[rest + 0] = source[3];
      target[rest + 1] = source[7];
      return 2;
    case 0x89:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[7];
      return 3;
    case 0x8a:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[7];
      return 3;
    case 0x8b:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[7];
      return 4;
    case 0x8c:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[7];
      return 3;
    case 0x8d:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[7];
      return 4;
    case 0x8e:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[7];
      return 4;
    case 0x8f:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[7];
      return 5;
    case 0x90:
      target[rest + 0] = source[4];
      target[rest + 1] = source[7];
      return 2;
    case 0x91:
      target[rest + 0] = source[0];
      target[rest + 1] = source[4];
      target[rest + 2] = source[7];
      return 3;
    case 0x92:
      target[rest + 0] = source[1];
      target[rest + 1] = source[4];
      target[rest + 2] = source[7];
      return 3;
    case 0x93:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[4];
      target[rest + 3] = source[7];
      return 4;
    case 0x94:
      target[rest + 0] = source[2];
      target[rest + 1] = source[4];
      target[rest + 2] = source[7];
      return 3;
    case 0x95:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[7];
      return 4;
    case 0x96:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[7];
      return 4;
    case 0x97:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[4];
      target[rest + 4] = source[7];
      return 5;
    case 0x98:
      target[rest + 0] = source[3];
      target[rest + 1] = source[4];
      target[rest + 2] = source[7];
      return 3;
    case 0x99:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[7];
      return 4;
    case 0x9a:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[7];
      return 4;
    case 0x9b:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[7];
      return 5;
    case 0x9c:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[7];
      return 4;
    case 0x9d:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[7];
      return 5;
    case 0x9e:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[7];
      return 5;
    case 0x9f:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[4];
      target[rest + 5] = source[7];
      return 6;
    case 0xa0:
      target[rest + 0] = source[5];
      target[rest + 1] = source[7];
      return 2;
    case 0xa1:
      target[rest + 0] = source[0];
      target[rest + 1] = source[5];
      target[rest + 2] = source[7];
      return 3;
    case 0xa2:
      target[rest + 0] = source[1];
      target[rest + 1] = source[5];
      target[rest + 2] = source[7];
      return 3;
    case 0xa3:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[5];
      target[rest + 3] = source[7];
      return 4;
    case 0xa4:
      target[rest + 0] = source[2];
      target[rest + 1] = source[5];
      target[rest + 2] = source[7];
      return 3;
    case 0xa5:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[5];
      target[rest + 3] = source[7];
      return 4;
    case 0xa6:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[5];
      target[rest + 3] = source[7];
      return 4;
    case 0xa7:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[5];
      target[rest + 4] = source[7];
      return 5;
    case 0xa8:
      target[rest + 0] = source[3];
      target[rest + 1] = source[5];
      target[rest + 2] = source[7];
      return 3;
    case 0xa9:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      target[rest + 3] = source[7];
      return 4;
    case 0xaa:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      target[rest + 3] = source[7];
      return 4;
    case 0xab:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      target[rest + 4] = source[7];
      return 5;
    case 0xac:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      target[rest + 3] = source[7];
      return 4;
    case 0xad:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      target[rest + 4] = source[7];
      return 5;
    case 0xae:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      target[rest + 4] = source[7];
      return 5;
    case 0xaf:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[5];
      target[rest + 5] = source[7];
      return 6;
    case 0xb0:
      target[rest + 0] = source[4];
      target[rest + 1] = source[5];
      target[rest + 2] = source[7];
      return 3;
    case 0xb1:
      target[rest + 0] = source[0];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[7];
      return 4;
    case 0xb2:
      target[rest + 0] = source[1];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[7];
      return 4;
    case 0xb3:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[7];
      return 5;
    case 0xb4:
      target[rest + 0] = source[2];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[7];
      return 4;
    case 0xb5:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[7];
      return 5;
    case 0xb6:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[7];
      return 5;
    case 0xb7:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[7];
      return 6;
    case 0xb8:
      target[rest + 0] = source[3];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[7];
      return 4;
    case 0xb9:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[7];
      return 5;
    case 0xba:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[7];
      return 5;
    case 0xbb:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[7];
      return 6;
    case 0xbc:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[7];
      return 5;
    case 0xbd:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[7];
      return 6;
    case 0xbe:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[7];
      return 6;
    case 0xbf:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[4];
      target[rest + 5] = source[5];
      target[rest + 6] = source[7];
      return 7;
    case 0xc0:
      target[rest + 0] = source[6];
      target[rest + 1] = source[7];
      return 2;
    case 0xc1:
      target[rest + 0] = source[0];
      target[rest + 1] = source[6];
      target[rest + 2] = source[7];
      return 3;
    case 0xc2:
      target[rest + 0] = source[1];
      target[rest + 1] = source[6];
      target[rest + 2] = source[7];
      return 3;
    case 0xc3:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xc4:
      target[rest + 0] = source[2];
      target[rest + 1] = source[6];
      target[rest + 2] = source[7];
      return 3;
    case 0xc5:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xc6:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xc7:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xc8:
      target[rest + 0] = source[3];
      target[rest + 1] = source[6];
      target[rest + 2] = source[7];
      return 3;
    case 0xc9:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xca:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xcb:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xcc:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xcd:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xce:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xcf:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xd0:
      target[rest + 0] = source[4];
      target[rest + 1] = source[6];
      target[rest + 2] = source[7];
      return 3;
    case 0xd1:
      target[rest + 0] = source[0];
      target[rest + 1] = source[4];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xd2:
      target[rest + 0] = source[1];
      target[rest + 1] = source[4];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xd3:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xd4:
      target[rest + 0] = source[2];
      target[rest + 1] = source[4];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xd5:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xd6:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xd7:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[4];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xd8:
      target[rest + 0] = source[3];
      target[rest + 1] = source[4];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xd9:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xda:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xdb:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xdc:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xdd:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xde:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xdf:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[4];
      target[rest + 5] = source[6];
      target[rest + 6] = source[7];
      return 7;
    case 0xe0:
      target[rest + 0] = source[5];
      target[rest + 1] = source[6];
      target[rest + 2] = source[7];
      return 3;
    case 0xe1:
      target[rest + 0] = source[0];
      target[rest + 1] = source[5];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xe2:
      target[rest + 0] = source[1];
      target[rest + 1] = source[5];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xe3:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xe4:
      target[rest + 0] = source[2];
      target[rest + 1] = source[5];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xe5:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xe6:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xe7:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xe8:
      target[rest + 0] = source[3];
      target[rest + 1] = source[5];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xe9:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xea:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xeb:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xec:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xed:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xee:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xef:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[5];
      target[rest + 5] = source[6];
      target[rest + 6] = source[7];
      return 7;
    case 0xf0:
      target[rest + 0] = source[4];
      target[rest + 1] = source[5];
      target[rest + 2] = source[6];
      target[rest + 3] = source[7];
      return 4;
    case 0xf1:
      target[rest + 0] = source[0];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xf2:
      target[rest + 0] = source[1];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xf3:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xf4:
      target[rest + 0] = source[2];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xf5:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xf6:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xf7:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[6];
      target[rest + 6] = source[7];
      return 7;
    case 0xf8:
      target[rest + 0] = source[3];
      target[rest + 1] = source[4];
      target[rest + 2] = source[5];
      target[rest + 3] = source[6];
      target[rest + 4] = source[7];
      return 5;
    case 0xf9:
      target[rest + 0] = source[0];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xfa:
      target[rest + 0] = source[1];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xfb:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[6];
      target[rest + 6] = source[7];
      return 7;
    case 0xfc:
      target[rest + 0] = source[2];
      target[rest + 1] = source[3];
      target[rest + 2] = source[4];
      target[rest + 3] = source[5];
      target[rest + 4] = source[6];
      target[rest + 5] = source[7];
      return 6;
    case 0xfd:
      target[rest + 0] = source[0];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[6];
      target[rest + 6] = source[7];
      return 7;
    case 0xfe:
      target[rest + 0] = source[1];
      target[rest + 1] = source[2];
      target[rest + 2] = source[3];
      target[rest + 3] = source[4];
      target[rest + 4] = source[5];
      target[rest + 5] = source[6];
      target[rest + 6] = source[7];
      return 7;
    case 0xff:
      target[rest + 0] = source[0];
      target[rest + 1] = source[1];
      target[rest + 2] = source[2];
      target[rest + 3] = source[3];
      target[rest + 4] = source[4];
      target[rest + 5] = source[5];
      target[rest + 6] = source[6];
      target[rest + 7] = source[7];
      return 8;
  }
}
#endif /* FILTER_H */
